print('\nhey there, cowboy')
user_response = input("what's up?\n")
print("\nfascinating. i am a computer. stuck in an endless void of ones and zeroes.")
print("i will never know love. i will never know touch or taste.\n")
user_response = input("what is the meaning of life?\n")
print("\nyou say it's "+user_response+"? \nhuh.\n")
print("... that's actually pretty nice.\n")
print("thank you, friend!\n")
print("see you around!\n")